name: E-Commerce CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Verify Project Structure
      - name: Verify Files
        run: |
          pwd
          ls -la
          ls -la backend
          ls -la kubernetes

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"  

      # Verify Docker Username
      - name: Verify Docker Username
        run: |
          echo "Docker Username = ${{ secrets.DOCKER_USERNAME }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest ./backend

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-app:latest

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # Configure Kubernetes
      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Verify Cluster
      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/
